### ISSUE TITLE
Bulk Insert

### ISSUE THREAD

**Issue by Kencho5** [ravenyue/ImageMatchNet#2]
Hello,

i noticed that there is no function to bulk insert images. i tried making my own and succeeded, but i noticed that making the signature data using **MakeSignatureData()** function is pretty slow compared to python's image-match module. it took 0.4 seconds on average to generate signature data in python and it takes 1.2 seconds in ImageMatchNet. what could be the case here?

thanks.

**Comment by ravenyue** [comment]
Hello @Kencho5 
I did benchmarking and the insertion didn't take very long. Can you explain your specific scenario and how to reproduce it?

Benchmarking source code: [ImageMatchNetBenchmark.zip](https://github.com/ravenyue/ImageMatchNet/files/7779422/ImageMatchNetBenchmark.zip)

![image](https://user-images.githubusercontent.com/50724541/147455250-1fb7de0c-1e1c-41c2-8d28-b7128b573cd3.png)

**Comment by Kencho5** [comment]
i noticed that i was calling the same function in a loop which was slowing down things. does ImageMatchNet have bulk insert or i have to implement that myself? sorry for the trouble

**Comment by ravenyue** [comment]
@Kencho5 Currently there is no bulk insert method. I use the following code for bulk insertion and it doesn't take long
I don't know how you do it, can you provide your code?
```csharp
var path = Path.Combine(Directory.GetCurrentDirectory(), "images/1.jpg");
var storage = new ElasticsearchSignatureStorage("http://localhost:9200");
var sw = new Stopwatch();
for (int i = 0; i < 1000; i++)
{
    var key = Path.GetRandomFileName();
    sw.Start();
    storage.AddOrUpdateImage(key, path);
    sw.Stop();
    Console.WriteLine($"Inserted Key:'{key}', Elapsed:{sw.ElapsedMilliseconds}ms");
    sw.Restart();
}
```
![image](https://user-images.githubusercontent.com/50724541/147549700-2d6c910f-9b62-4050-baaf-39cefe3afc5b.png)

**Comment by Kencho5** [comment]
i needed to insert images from urls so i had to make an async function which takes urls, gets image bytes from around 5,000 images, created signature data using your functions from ImageMatchNet, appends those signature data objects to list and bulk inserts into elastic. takes around 4-5 seconds. i can share code if you need it

**Comment by ravenyue** [comment]
Please provide the code that can reproduce the issue
