### ISSUE TITLE
Signatures not matching

### ISSUE THREAD

**Issue by Kencho5** [ravenyue/ImageMatchNet#3]
hello,

i've noticed that on these 2 images: 
[image1](https://community.akamai.steamstatic.com/market/image/nOPj8NByn7qxdU_ypFhe7oHkwJ5nT8nF2mODXk1INU8fLFHQ9D5dVXoLcXsoyfM3TWT8zf2kSOUYSYXkLrQMpyVtuCVggdSrNebBbpS9XSL6s_Gh3JDZv7-4ouT7Kl3u5qDFaxZ1ssSMZkqtFeyC1pHHPcTk_jy_8D1GedvlSHlG/avatar.jpg) 
[image2](https://cdn.akamai.steamstatic.com/steamcommunity/public/images/avatars/ff/ff7f690382c777ebfa2d943cf083557d9e897be5.jpg) 
signatures don't match, but when using the python version of image-match the signatures are both the same. is this an issue or a feature?

**Comment by ravenyue** [comment]
@Kencho5  After my test, these two images are matched with a normalized distance of `0.06046166912030474`
Do not crop images when the image size is small, as this will reduce the critical information needed for the algorithm to match.

**Comment by Kencho5** [comment]
i am not cropping the images. is ImageMatchNet cropping by default?

**Comment by ravenyue** [comment]
The normalized distance is less than 0.4 for both images above cropped or uncropped. ImageMatchNet does not crop images by default.
Please explain how you got the not matching, and please provide the reproduce code.

**Comment by Kencho5** [comment]
```
var gis = new ImageSignature();

var sign1 = gis.GenerateSignature("image1.jpg");
var sign2 = gis.GenerateSignature("image2.jpg");

string signString1 = string.Join("",sign1.Select(i => i.ToString()).ToArray());
string signString2 = string.Join("",sign2.Select(i => i.ToString()).ToArray());
```
[image1](https://community.akamai.steamstatic.com/market/image/nOPj8NByn7qxdU_ypFhe7oHkwJ5nT8nF2mODXk1INU8fLFHQ9D5dVXoLcXsoyfM3TWT8zf2kSOUYSYXkLrQMpyVtuCVggdSrNebBbpS9XSL6s_Gh3JDZv7-4ouT7Kl3u5qDFaxZ1ssSMZkqtFeyC1pHHPcTk_jy_8D1GedvlSHlG/avatar.jpg)
[image2](https://cdn.akamai.steamstatic.com/steamcommunity/public/images/avatars/ff/ff7f690382c777ebfa2d943cf083557d9e897be5.jpg)

as you can see **signString1** and **signString2** are different here where in python doing the same thing outputs the same signatures

**Comment by ravenyue** [comment]
Yes, the two signatures are not the same because the pixels of the two images are not exactly the same.

The signature algorithm will do floating point operations, and because of the difference in floating point precision between python and c#, the results will be slightly different, but within the margin of error.

You should use the `gis.NormalizedDistance(sign1, sign2)` method to calculate the difference, instead of comparing signatures directly.

Usually the normalized distance is less than 0.40 is very likely to matches, the value should be adjusted on a case-by-case basis.
```csharp
var gis = new ImageSignature();

var sign1 = gis.GenerateSignature("image1.jpg");
var sign2 = gis.GenerateSignature("image2.jpg");

var dist = gis.NormalizedDistance(sign1, sign2);
Console.WriteLine(dist < 0.4);
```

**Comment by Kencho5** [comment]
i see. thanks!
